---
- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Create config file for br_netfilter module
  file:
    path: /etc/modules-load.d/k8s.config
    state: file
    owner: root
    group: root
    mode: 0644

- name: Write config file for br_netfilter module
  lineinfile:
    path: /etc/modules-load.d/k8s.config
    line: br_netfilter

- name: Load br_netfilter module
  modprobe:
    name: modprobe br_netfilter
    state: present

- name: Configure sysctl
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items: "{{ sysctl_params }}"
  register: result_sysctl_config

- name: Reload sysctl
  command: sysctl --system
  when: result_sysctl_config is changed
