---
- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Create config file for br_netfilter module
  copy:
    content: "br_netfilter"
    dest: /etc/modules-load.d/k8s.config
    force: no
    owner: root
    group: root
    mode: 0644

- name: Load br_netfilter module
  modprobe:
    name: br_netfilter
    state: present

- name: Configure sysctl
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_dict: "{{ sysctl_params }}"
  notify: Reload sysctl
